#Page 583
x<-c(2,2,6,8,10)
y<-c(0,1,2,3,3)
fit<-lm(y~x)
print(fit)
beta_0<--0.125
beta_1<-0.3438
find<-function(x){
  y<-c((beta_1*x)+beta_0)
}
k<-find(x)
library("Metrics")
SSE<-sse(k,y)
sum_of_x<-sum(x[1],x[2],x[3],x[4],x[5])
sum_of_x_sq<-sum(x[1]**2,x[2]**2,x[3]**2,x[4]**2,x[5]**2)
n<-length(x)
SS_xx<-(sum_of_x_sq)-((1/n)*(sum_of_x)**2)
S_e<-sqrt(SSE/(n-2))
alpha<-1-0.95
df<-n-2
t<-qt(alpha/2,df)
Upper_interval<-print(beta_1+((t)*(S_e)/sqrt(SS_xx)))
Lower_interval<-print(beta_1-((t)*(S_e)/sqrt(SS_xx)))
